name: Unity - Request Activation File
on:
  workflow_dispatch:
jobs:
  requestActivation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-request-activation-file@v2
        with:
          # Match the same editor version you’ll build with
          unityVersion: 6000.2.10f1
      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: Unity_ActivationFile
          path: Unity_v*.alf
